export const PRODUCTS_LOAD_SUCCESS = "PRODUCTS_LOAD_SUCCESS";
export const PRODUCT_LOAD_COMMIT = "PRODUCT_LOAD_COMMIT";
export const PRODUCT_LOAD_ROLLBACK = "PRODUCT_LOAD_ROLLBACK";
export const MARK_FAOURITE = "MARK_FAOURITE";
export const UNMARK_FAOURITE = "UNMARK_FAOURITE";
export const ADD_PRODUCT = "ADD_PRODUCT"
export const ADD_PRODUCT_COMMIT = "ADD_PRODUCT_COMMIT";
export const USER_SAVE_SUCCESS = "USER_SAVE_SUCCESS";
