export const PRODUCTS_LOAD_SUCCESS = "PRODUCTS_LOAD_SUCCESS";
export const PRODUCT_LOAD_COMMIT = "PRODUCT_LOAD_COMMIT";
export const PRODUCT_LOAD_ROLLBACK = "PRODUCT_LOAD_ROLLBACK";
export const MARK_FAOURITE = "MARK_FAOURITE";